# -*- coding: UTF-8 -*-
# author:@Jack.Wang
# time :2018/8/21 9:15
"""
期货品种信息
品种名称
最小变动单位
保证金
手续费_固定
手续费_浮动
交易所代码
上市年份
上市月份
本地数据的最早年份
本地数据的最早月份
交易时段
交易时段模式
主力合约
"""
"""
商品期货数据当前所有品种
有色1 - 6: 铜 铝 锌 铅 镍 锡
贵金属7 - 8: 金 银
黑色9 - 13: 螺纹 热卷 铁矿 焦煤 焦炭
铁合金14 - 15：硅铁 锰硅
建材16 - 17: 沥青 玻璃
电力原料18: 动力煤
油脂油料19 - 25: 豆粕 豆油 豆一 豆二 棕榈油 菜粕 菜油
谷物26 - 27: 玉米 玉米淀粉
饲料下游28: 鸡蛋
软商29 - 30: 白糖 棉花
鲜果31: 苹果
其它农产品32: 橡胶
化工33 - 37: 塑料 PVC PP PTA 甲醇
能源38：原油 燃油
不活跃品种
胶板 纤板 棉纱 郑麦 早稻 晚稻 粳稻 菜籽
"""

"""
股指
IF沪深300
IH上证50
IC中证500
国债
TF5年国债
T十年国债
"""
import datetime

class futures_info:
    def __init__(self):
        self.today = datetime.datetime.strftime(datetime.datetime.now(), '%Y-%m-%d')
    # 所有期货品种的list，只提供这一个接口，接口写死，有需要就改这个接口
    def futures_list(self):
        finance_list = ['IF', 'IH', 'IC', 'TF', 'T', 'TS']
        commodity_list = [
            'CU', 'AL', 'ZN', 'PB', 'NI', 'SN',
            'AU', 'AG',
            'RB', 'HC', 'I', 'JM', 'J',
            'SF', 'SM',
            'BU', 'FG',
            'ZC',
            'M', 'Y', 'A', 'B', 'P', 'RM', 'OI',
            'C', 'CS',
            'JD',
            'SR', 'CF',
            'AP',
            'RU',
            'L', 'V', 'PP', 'TA', 'MA',
            'FU', 'SC']
        futures_list = []
        for i in commodity_list:
            futures_list.append(i)
        for i in finance_list:
            futures_list.append(i)

        return commodity_list, finance_list, futures_list

    # 所有期货品种的info，只提供这一个接口，接口写死，有需要改这个接口
    def futures_info(self):
        endtime = '2018-08-21 15:30:00'
        phase=[['21:00:00', '23:00:00'],
               ['23:00:01', '23:30:00'],
               ['23:30:01', '23:59:59'],
               ['00:00:00', '01:00:00'],
               ['01:00:01', '02:30:00'],
               ['09:00:00', '10:15:00'],
               ['10:30:00', '11:30:00'],
               ['13:30:00', '15:00:00'],
               ]

        commodity = [
            'CU','AL','ZN','PB','NI','SN',
            'AU','AG',
            'RB','HC','I','JM','J',
            'SF','SM',
            'BU','FG',
            'ZC',
            'M','Y','A','B','P','RM','OI',
            'C','CS',
            'JD',
            'SR','CF',
            'AP',
            'RU',
            'L','V','PP','TA','MA',
            'FU','SC'
            'BB','FB','CY','WH','RI','LR','JR','RS']
        finance = ['IF','IH','IC','TF','T','TS']
        commodity_info = {}
        """
        品种名称
        最小变动单位
        保证金
        手续费_固定
        手续费_浮动
        交易所代码
        上市年份
        上市月份
        本地数据的最早年份
        本地数据的最早月份
        交易时段
        交易时段模式
        主力合约
        """
        cu_dict = {'code':'cu',
                   'trading_unit': 5,
                   'min_change': 10,
                   'margin': 0.07,
                   'commission_fix': 0,
                   'commission_float': 0.00005,
                   'commission_fix_today': 0,
                   'commission_float_today': 0,
                   'exchange_id':'shfe',
                   'ipo':'1993-03-01',
                   'begintime_local':'2013-12-20 21:00:00',
                   'endtime_local': endtime,
                   'trading_period': [
                                     ['21:00:00', '23:59:59'],
                                     ['00:00:00', '01:00:00'],
                                     ['09:00:00', '10:15:00'],
                                     ['10:30:00', '11:30:00'],
                                     ['13:30:00', '15:00:00']],
                   'trading_period_mode': '4',
                   'domi_month':['01', '02', '03', '04', '05', '06',
                                 '07', '08', '09', '10', '11', '12'],
                   }
        al_dict = {'code': 'al',
                   'trading_unit': 5,
                   'min_change': 5,
                   'margin': 0.07,
                   'commission_fix': 3,
                   'commission_float': 0,
                   'commission_fix_today': 0,
                   'commission_float_today': 0,
                   'exchange_id': 'shfe',
                   'ipo': '1992-05-28',
                   'begintime_local':'2013-12-20 21:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['21:00:00', '23:59:59'],
                                      ['00:00:00', '01:00:00'],
                                      ['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00'],
                                      ],
                   'trading_period_mode': '4',
                   'domi_month': ['01', '02', '03', '04', '05', '06',
                                  '07', '08', '09', '10', '11', '12'],
                   }
        zn_dict = {'code': 'zn',
                   'trading_unit': 5,
                   'min_change': 5,
                   'margin': 0.08,
                   'commission_fix': 3,
                   'commission_float': 0,
                   'commission_fix_today': 0,
                   'commission_float_today': 0,
                   'exchange_id': 'shfe',
                   'ipo': '2007-03-26',
                   'begintime_local':'2013-12-20 21:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['21:00:00', '23:59:59'],
                                      ['00:00:00', '01:00:00'],
                                      ['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00'],
                                      ],
                   'trading_period_mode': '4',
                   'domi_month': ['01', '02', '03', '04', '05', '06',
                                  '07', '08', '09', '10', '11', '12'],
                   }
        pb_dict = {'code': 'pb',
                   'trading_unit': 5,
                   'min_change': 5,
                   'margin': 0.08,
                   'commission_fix': 0,
                   'commission_float': 0.00004,
                   'commission_fix_today': 0,
                   'commission_float_today': 0,
                   'exchange_id': 'shfe',
                   'ipo': '2011-03-24',
                   'begintime_local':'2013-12-20 21:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['21:00:00', '23:59:59'],
                                      ['00:00:00', '01:00:00'],
                                      ['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00'],
                                      ],
                   'trading_period_mode': '4',
                   'domi_month': ['01', '02', '03', '04', '05', '06',
                                  '07', '08', '09', '10', '11', '12'],
                   }
        ni_dict = {'code': 'ni',
                   'trading_unit': 1,
                   'min_change': 10,
                   'margin': 0.08,
                   'commission_fix': 6,
                   'commission_float': 0,
                   'commission_fix_today': 6,
                   'commission_float_today': 0,
                   'exchange_id': 'shfe',
                   'ipo': '2015-03-27',
                   'begintime_local':'2015-03-27 21:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['21:00:00', '23:59:59'],
                                      ['00:00:00', '01:00:00'],
                                      ['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00'],
                                      ],
                   'trading_period_mode': '4',
                   'domi_month': ['01', '03', '05', '07', '09', '11'],
                   }
        sn_dict = {'code': 'sn',
                   'trading_unit': 1,
                   'min_change': 10,
                   'margin': 0.07,
                   'commission_fix': 3,
                   'commission_float': 0,
                   'commission_fix_today': 0,
                   'commission_float_today': 0,
                   'exchange_id': 'shfe',
                   'ipo': '2015-03-27',
                   'begintime_local':'2015-03-27 21:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['21:00:00', '23:59:59'],
                                      ['00:00:00', '01:00:00'],
                                      ['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00'],
                                      ],
                   'trading_period_mode': '4',
                   'domi_month': ['01', '05', '09'],
                   }
        au_dict = {'code': 'au',
                   'trading_unit': 1000,
                   'min_change': 0.05,
                   'margin': 0.05,
                   'commission_fix': 10,
                   'commission_float': 0,
                   'commission_fix_today': 0,
                   'commission_float_today': 0,
                   'exchange_id': 'shfe',
                   'ipo': '2008-01-09',
                   'begintime_local':'2013-07-05 21:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['21:00:00', '23:59:59'],
                                      ['00:00:00', '01:00:00'],
                                      ['01:00:01', '02:30:00'],
                                      ['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00'],
                                      ],
                   'trading_period_mode': '5',
                   'domi_month': ['06', '12'],
                   }
        ag_dict = {'code': 'ag',
                   'trading_unit': 15,
                   'min_change': 1,
                   'margin': 0.06,
                   'commission_fix': 0,
                   'commission_float': 0.0005,
                   'commission_fix_today': 0,
                   'commission_float_today': 0.0005,
                   'exchange_id': 'shfe',
                   'ipo': '2012-05-10',
                   'begintime_local':'2013-07-05 21:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['21:00:00', '23:59:59'],
                                      ['00:00:00', '01:00:00'],
                                      ['01:00:01', '02:30:00'],
                                      ['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00'],
                                      ],
                   'trading_period_mode': 'au',
                   'domi_month': ['06', '12'],
                   }
        rb_dict = {'code': 'rb',
                   'trading_unit': 10,
                   'min_change': 1,
                   'margin': 0.09,
                   'commission_fix': 0,
                   'commission_float': 0.0001,
                   'commission_fix_today': 0,
                   'commission_float_today': 0.0001,
                   'exchange_id': 'shfe',
                   'ipo': '2009-03-27',
                   'begintime_local':'2014-12-26 21:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['21:00:00', '23:00:00'],
                                      ['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00'],
                                      ],
                   'trading_period_mode': '2',
                   'domi_month': ['01', '05', '10'],
                   }
        hc_dict = {'code': 'hc',
                   'trading_unit': 10,
                   'min_change': 1,
                   'margin': 0.09,
                   'commission_fix': 0,
                   'commission_float': 0.0001,
                   'commission_fix_today': 0,
                   'commission_float_today': 0.0001,
                   'exchange_id': 'shfe',
                   'ipo': '2014-03-21',
                   'begintime_local':'2014-12-26 21:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['21:00:00', '23:00:00'],
                                      ['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00'],
                                      ],
                   'trading_period_mode': '2',
                   'domi_month': ['01', '05', '10'],
                   }
        i_dict = {'code': 'i',
                  'trading_unit': 100,
                  'min_change': 0.5,
                  'margin': 0.05,
                  'commission_fix': 0,
                  'commission_float': 0.00006,
                  'commission_fix_today': 0,
                  'commission_float_today': 0.00012,
                  'exchange_id': 'dce',
                  'ipo': '2013-10-18',
                  'begintime_local': '2014-12-26 21:00:00',
                  'endtime_local': endtime,
                  'trading_period': [['21:00:00', '23:30:00'],
                                     ['09:00:00', '10:15:00'],
                                     ['10:30:00', '11:30:00'],
                                     ['13:30:00', '15:00:00'],
                                    ],
                  'trading_period_mode': '3',
                  'domi_month': ['01', '05', '09'],
                   }
        jm_dict = {'code': 'jm',
                   'trading_unit': 60,
                   'min_change': 0.5,
                   'margin': 0.12,
                   'commission_fix': 0,
                   'commission_float': 0.00006,
                   'commission_fix_today': 0,
                   'commission_float_today': 0.00018,
                   'exchange_id': 'dce',
                   'ipo': '2013-03-22',
                   'begintime_local': '2014-12-26 21:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['21:00:00', '23:30:00'],
                                      ['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00'],
                                     ],
                   'trading_period_mode': '3',
                   'domi_month': ['01', '05', '09'],
                  }
        j_dict = {'code': 'j',
                   'trading_unit': 100,
                   'min_change': 0.5,
                   'margin': 0.12,
                   'commission_fix': 0,
                   'commission_float': 0.00006,
                   'commission_fix_today': 0,
                   'commission_float_today': 0.00018,
                   'exchange_id': 'dce',
                   'ipo': '2011-04-15',
                   'begintime_local': '2014-07-04 21:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['21:00:00', '23:30:00'],
                                      ['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00'],
                                      ],
                   'trading_period_mode': '3',
                   'domi_month': ['01', '05', '09'],
                   }
        sf_dict = {'code': 'sf',
                  'trading_unit': 5,
                  'min_change': 2,
                  'margin': 0.07,
                  'commission_fix': 3,
                  'commission_float': 0,
                  'commission_fix_today': 9,
                  'commission_float_today': 0,
                  'exchange_id': 'czce',
                  'ipo': '2014-08-08',
                  'begintime_local': '2014-08-08 21:00:00',
                  'endtime_local': endtime,
                  'trading_period': [['09:00:00', '10:15:00'],
                                     ['10:30:00', '11:30:00'],
                                     ['13:30:00', '15:00:00']],
                  'trading_period_mode': '1',
                  'domi_month': ['01', '05', '09'],
                  }
        sm_dict = {'code': 'sm',
                   'trading_unit': 5,
                   'min_change': 2,
                   'margin': 0.07,
                   'commission_fix': 3,
                   'commission_float': 0,
                   'commission_fix_today': 6,
                   'commission_float_today': 0,
                   'exchange_id': 'czce',
                   'ipo': '2014-08-08',
                   'begintime_local': '2014-08-08 21:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00']],
                   'trading_period_mode': '1',
                   'domi_month': ['01', '05', '09'],
                   }

        bu_dict = {'code': 'bu',
                   'trading_unit': 10,
                   'min_change': 2,
                   'margin': 0.08,
                   'commission_fix': 0,
                   'commission_float': 0.0001,
                   'commission_fix_today': 0,
                   'commission_float_today': 0,
                   'exchange_id': 'shfe',
                   'ipo': '2013-10-09',
                   'begintime_local': '2015-09-28 21:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['21:00:00', '23:00:00'],
                                      ['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00'],
                                      ],
                   'trading_period_mode': '2',
                   'domi_month': ['06', '12'],
                   }
        fg_dict = {'code': 'fg',
                   'trading_unit': 20,
                   'min_change': 1,
                   'margin': 0.07,
                   'commission_fix': 3,
                   'commission_float': 0,
                   'commission_fix_today': 6,
                   'commission_float_today': 0,
                   'exchange_id': 'czce',
                   'ipo': '2012-12-03',
                   'begintime_local': '2015-06-11 21:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['21:00:00', '23:30:00'],
                                      ['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00'],
                                      ],
                   'trading_period_mode': '3',
                   'domi_month': ['01', '05', '09'],
                   }
        zc_dict = {'code': 'zc',
                   'trading_unit': 100,
                   'min_change': 0.2,
                   'margin': 0.08,
                   'commission_fix': 4,
                   'commission_float': 0,
                   'commission_fix_today': 4,
                   'commission_float_today': 0,
                   'exchange_id': 'czce',
                   'ipo': '2013-09-26',
                   'begintime_local': '2015-12-17 21:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['21:00:00', '23:30:00'],
                                      ['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00'],
                                      ],
                   'trading_period_mode': '3',
                   'domi_month': ['01', '05', '09'],
                   }
        m_dict = {'code': 'm',
                   'trading_unit': 10,
                   'min_change': 1,
                   'margin': 0.05,
                   'commission_fix': 1.5,
                   'commission_float': 0,
                   'commission_fix_today': 1.5,
                   'commission_float_today': 0,
                   'exchange_id': 'dce',
                   'ipo': '2000-07-17',
                   'begintime_local': '2014-12-26 21:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['21:00:00', '23:30:00'],
                                      ['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00'],
                                      ],
                   'trading_period_mode': '3',
                   'domi_month': ['01', '05', '09'],
                   }
        y_dict = {'code': 'y',
                  'trading_unit': 10,
                  'min_change': 2,
                  'margin': 0.07,
                  'commission_fix': 2.5,
                  'commission_float': 0,
                  'commission_fix_today': 2.5,
                  'commission_float_today': 0,
                  'exchange_id': 'dce',
                  'ipo': '2006-01-09',
                  'begintime_local': '2014-12-26 21:00:00',
                  'endtime_local': endtime,
                  'trading_period': [['21:00:00', '23:30:00'],
                                     ['09:00:00', '10:15:00'],
                                     ['10:30:00', '11:30:00'],
                                     ['13:30:00', '15:00:00'],
                                     ],
                  'trading_period_mode': '3',
                  'domi_month': ['01', '05', '09'],
                  }
        a_dict = {'code': 'a',
                  'trading_unit': 10,
                  'min_change': 1,
                  'margin': 0.07,
                  'commission_fix': 2,
                  'commission_float': 0,
                  'commission_fix_today': 2,
                  'commission_float_today': 0,
                  'exchange_id': 'dce',
                  'ipo': '2002-03-15',
                  'begintime_local': '2014-12-26 21:00:00',
                  'endtime_local': endtime,
                  'trading_period': [['21:00:00', '23:30:00'],
                                     ['09:00:00', '10:15:00'],
                                     ['10:30:00', '11:30:00'],
                                     ['13:30:00', '15:00:00'],
                                     ],
                  'trading_period_mode': '3',
                  'domi_month': ['01', '05', '09'],
                  }
        b_dict = {'code': 'b',
                  'trading_unit': 10,
                  'min_change': 1,
                  'margin': 0.07,
                  'commission_fix': 1,
                  'commission_float': 0,
                  'commission_fix_today': 1,
                  'commission_float_today': 0,
                  'exchange_id': 'dce',
                  'ipo': '2004-12-22',
                  'begintime_local': '2018-04-09 21:00:00',
                  'endtime_local': endtime,
                  'trading_period': [['21:00:00', '23:30:00'],
                                     ['09:00:00', '10:15:00'],
                                     ['10:30:00', '11:30:00'],
                                     ['13:30:00', '15:00:00'],
                                     ],
                  'trading_period_mode': '3',
                  'domi_month': ['01', '05', '09'],
                  }
        p_dict = {'code': 'p',
                  'trading_unit': 10,
                  'min_change': 2,
                  'margin': 0.07,
                  'commission_fix': 2.5,
                  'commission_float': 0,
                  'commission_fix_today': 2.5,
                  'commission_float_today': 0,
                  'exchange_id': 'dce',
                  'ipo': '2014-07-04',
                  'begintime_local': '2018-04-09 21:00:00',
                  'endtime_local': endtime,
                  'trading_period': [['21:00:00', '23:30:00'],
                                     ['09:00:00', '10:15:00'],
                                     ['10:30:00', '11:30:00'],
                                     ['13:30:00', '15:00:00'],
                                     ],
                  'trading_period_mode': '3',
                  'domi_month': ['01', '05', '09'],
                  }
        rm_dict = {'code': 'rm',
                  'trading_unit': 10,
                  'min_change': 1,
                  'margin': 0.06,
                  'commission_fix': 1.5,
                  'commission_float': 0,
                  'commission_fix_today': 0,
                  'commission_float_today': 0,
                  'exchange_id': 'czce',
                  'ipo': '2014-12-12',
                  'begintime_local': '2014-12-12 21:00:00',
                  'endtime_local': endtime,
                  'trading_period': [['21:00:00', '23:30:00'],
                                     ['09:00:00', '10:15:00'],
                                     ['10:30:00', '11:30:00'],
                                     ['13:30:00', '15:00:00'],
                                     ],
                  'trading_period_mode': '3',
                  'domi_month': ['01', '05', '09'],
                  }
        oi_dict = {'code': 'oi',
                   'trading_unit': 10,
                   'min_change': 1,
                   'margin': 0.07,
                   'commission_fix': 2,
                   'commission_float': 0,
                   'commission_fix_today': 0,
                   'commission_float_today': 0,
                   'exchange_id': 'czce',
                   'ipo': '2007-06-08',
                   'begintime_local': '2016-06-11 21:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['21:00:00', '23:30:00'],
                                      ['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00'],
                                      ],
                   'trading_period_mode': '3',
                   'domi_month': ['01', '05', '09'],
                   }
        c_dict = {'code': 'c',
                   'trading_unit': 10,
                   'min_change': 1,
                   'margin': 0.07,
                   'commission_fix': 1.2,
                   'commission_float': 0,
                   'commission_fix_today': 0,
                   'commission_float_today': 0,
                   'exchange_id': 'dce',
                   'ipo': '2004-09-22',
                   'begintime_local': '2008-07-10 09:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00']],
                   'trading_period_mode': '1',
                   'domi_month': ['01', '05', '09'],
                   }
        cs_dict = {'code': 'cs',
                  'trading_unit': 10,
                  'min_change': 1,
                  'margin': 0.07,
                  'commission_fix': 1.5,
                  'commission_float': 0,
                  'commission_fix_today': 1.5,
                  'commission_float_today': 0,
                  'exchange_id': 'dce',
                  'ipo': '2014-12-19',
                  'begintime_local': '2014-12-19 09:00:00',
                  'endtime_local': endtime,
                  'trading_period': [['09:00:00', '10:15:00'],
                                     ['10:30:00', '11:30:00'],
                                     ['13:30:00', '15:00:00']],
                  'trading_period_mode': '1',
                  'domi_month': ['01', '05', '09'],
                  }
        jd_dict = {'code': 'jd',
                   'trading_unit': 10,
                   'min_change': 1,
                   'margin': 0.08,
                   'commission_fix': 0,
                   'commission_float': 0.00015,
                   'commission_fix_today': 0,
                   'commission_float_today': 0.00015,
                   'exchange_id': 'dce',
                   'ipo': '2013-11-08',
                   'begintime_local': '2013-11-08 09:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00']],
                   'trading_period_mode': '1',
                   'domi_month': ['01', '05', '09'],
                   }
        sr_dict = {'code': 'sr',
                   'trading_unit': 10,
                   'min_change': 1,
                   'margin': 0.05,
                   'commission_fix': 3,
                   'commission_float': 0,
                   'commission_fix_today': 0,
                   'commission_float_today': 0,
                   'exchange_id': 'czce',
                   'ipo': '2006-01-06',
                   'begintime_local': '2014-12-12 09:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['21:00:00', '23:30:00'],
                                      ['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00'],
                                      ],
                   'trading_period_mode': '3',
                   'domi_month': ['01', '05', '09'],
                   }
        cf_dict = {'code': 'cf',
                   'trading_unit': 5,
                   'min_change': 5,
                   'margin': 0.07,
                   'commission_fix': 4.3,
                   'commission_float': 0,
                   'commission_fix_today': 0,
                   'commission_float_today': 0,
                   'exchange_id': 'czce',
                   'ipo': '2004-06-01',
                   'begintime_local': '2014-12-12 09:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['21:00:00', '23:30:00'],
                                      ['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00'],
                                      ],
                   'trading_period_mode': '3',
                   'domi_month': ['01', '05', '09'],
                   }
        ap_dict = {'code': 'ap',
                   'trading_unit': 10,
                   'min_change': 1,
                   'margin': 0.11,
                   'commission_fix': 20,
                   'commission_float': 0,
                   'commission_fix_today': 20,
                   'commission_float_today': 0,
                   'exchange_id': 'czce',
                   'ipo': '2017-12-22',
                   'begintime_local': '2017-12-25 09:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00']],
                   'trading_period_mode': '1',
                   'domi_month': ['01', '05', '09'],
                   }
        ru_dict = {'code': 'ru',
                   'trading_unit': 10,
                   'min_change': 5,
                   'margin': 0.09,
                   'commission_fix': 0,
                   'commission_float': 0.000045,
                   'commission_fix_today': 0,
                   'commission_float_today': 0.000045,
                   'exchange_id': 'shfe',
                   'ipo': '1993-11-30',
                   'begintime_local': '2014-12-26 09:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['21:00:00', '23:00:00'],
                                      ['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00'],
                                      ],
                   'trading_period_mode': '2',
                   'domi_month': ['01', '05', '09'],
                   }
        l_dict = {'code': 'l',
                   'trading_unit': 5,
                   'min_change': 5,
                   'margin': 0.07,
                   'commission_fix': 2,
                   'commission_float': 0,
                   'commission_fix_today': 2,
                   'commission_float_today': 0,
                   'exchange_id': 'dce',
                   'ipo': '2007-07-31',
                   'begintime_local': '2008-06-25 09:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00']],
                   'trading_period_mode': '1',
                   'domi_month': ['01', '05', '09'],
                   }
        v_dict = {'code': 'v',
                  'trading_unit': 5,
                  'min_change': 5,
                  'margin': 0.07,
                  'commission_fix': 2,
                  'commission_float': 0,
                  'commission_fix_today': 0,
                  'commission_float_today': 0,
                  'exchange_id': 'dce',
                  'ipo': '2009-05-25',
                  'begintime_local': '2009-05-25 09:00:00',
                  'endtime_local': endtime,
                  'trading_period': [['09:00:00', '10:15:00'],
                                     ['10:30:00', '11:30:00'],
                                     ['13:30:00', '15:00:00']],
                  'trading_period_mode': '1',
                  'domi_month': ['01', '05', '09'],
                  }
        pp_dict = {'code': 'pp',
                  'trading_unit': 5,
                  'min_change': 1,
                  'margin': 0.07,
                  'commission_fix': 0,
                  'commission_float': 0.00006,
                  'commission_fix_today': 0,
                  'commission_float_today': 0.00006,
                  'exchange_id': 'dce',
                  'ipo': '2014-02-28',
                  'begintime_local': '2014-02-28 09:00:00',
                  'endtime_local': endtime,
                  'trading_period': [['09:00:00', '10:15:00'],
                                     ['10:30:00', '11:30:00'],
                                     ['13:30:00', '15:00:00']],
                  'trading_period_mode': '1',
                  'domi_month': ['01', '05', '09'],
                  }
        ta_dict = {'code': 'ta',
                   'trading_unit': 5,
                   'min_change': 1,
                   'margin': 0.06,
                   'commission_fix': 3,
                   'commission_float': 0,
                   'commission_fix_today': 0,
                   'commission_float_today': 0,
                   'exchange_id': 'czce',
                   'ipo': '2006-12-18',
                   'begintime_local': '2014-12-12 21:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['21:00:00', '23:30:00'],
                                      ['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00'],
                                      ],
                   'trading_period_mode': '3',
                   'domi_month': ['01', '05', '09'],
                   }
        ma_dict = {'code': 'ma',
                   'trading_unit': 10,
                   'min_change': 1,
                   'margin': 0.07,
                   'commission_fix': 2,
                   'commission_float': 0,
                   'commission_fix_today': 6,
                   'commission_float_today': 0,
                   'exchange_id': 'czce',
                   'ipo': '2011-10-28',
                   'begintime_local': '2014-12-12 21:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['21:00:00', '23:30:00'],
                                      ['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00'],
                                      ],
                   'trading_period_mode': '3',
                   'domi_month': ['01', '05', '09'],
                   }
        sc_dict = {'code': 'sc',
                   'trading_unit': 1000,
                   'min_change': 0.1,
                   'margin': 0.07,
                   'commission_fix': 20,
                   'commission_float': 0,
                   'commission_fix_today': 20,
                   'commission_float_today': 0,
                   'exchange_id': 'ine',
                   'ipo': '2018-03-26',
                   'begintime_local': '2018-03-26 09:00:00',
                   'endtime_local': endtime,
                   'trading_period':[['21:00:00', '23:59:59'],
                                     ['00:00:00', '02:30:00'],
                                     ['09:00:00', '10:15:00'],
                                     ['10:30:00', '11:30:00'],
                                     ['13:30:00', '15:00:00'],
                                     ],
                   'trading_period_mode': '5',
                   'domi_month': ['01', '02', '03', '04', '05', '06',
                                  '07', '08', '09', '10', '11', '12'],
                   }
        fu_dict = {'code': 'fu',
                   'trading_unit': 10,
                   'min_change': 1,
                   'margin': 0.10,
                   'commission_fix': 0,
                   'commission_float': 0.00005,
                   'commission_fix_today': 0,
                   'commission_float_today': 0.00005,
                   'exchange_id': 'shfe',
                   'ipo': '2018-07-16',
                   'begintime_local': '2018-07-16 21:00:00',
                   'endtime_local': endtime,
                   'trading_period': [['21:00:00', '23:59:59'],
                                      ['00:00:00', '02:30:00'],
                                      ['09:00:00', '10:15:00'],
                                      ['10:30:00', '11:30:00'],
                                      ['13:30:00', '15:00:00'],
                                      ],
                   'trading_period_mode': '5',
                   'domi_month': ['01', '02', '03', '04', '05', '06',
                                  '07', '08', '09', '10', '11', '12'],
                   }





        commodity_info['cu'] = cu_dict
        commodity_info['al'] = al_dict
        commodity_info['zn'] = zn_dict
        commodity_info['pb'] = pb_dict
        commodity_info['ni'] = ni_dict
        commodity_info['sn'] = sn_dict
        commodity_info['au'] = au_dict
        commodity_info['ag'] = ag_dict
        commodity_info['rb'] = rb_dict
        commodity_info['hc'] = hc_dict
        commodity_info['i'] = i_dict
        commodity_info['jm'] = jm_dict
        commodity_info['j'] = j_dict
        commodity_info['sf'] = sf_dict
        commodity_info['sm'] = sm_dict
        commodity_info['bu'] = bu_dict
        commodity_info['fg'] = fg_dict
        commodity_info['zc'] = zc_dict
        commodity_info['m'] = m_dict
        commodity_info['y'] = y_dict
        commodity_info['a'] = a_dict
        commodity_info['b'] = b_dict
        commodity_info['p'] = p_dict
        commodity_info['rm'] = rm_dict
        commodity_info['oi'] = oi_dict
        commodity_info['c'] = c_dict
        commodity_info['cs'] = cs_dict
        commodity_info['jd'] = jd_dict
        commodity_info['sr'] = sr_dict
        commodity_info['cf'] = cf_dict
        commodity_info['ap'] = ap_dict
        commodity_info['ru'] = ru_dict
        commodity_info['l'] = l_dict
        commodity_info['v'] = v_dict
        commodity_info['pp'] = pp_dict
        commodity_info['ta'] = ta_dict
        commodity_info['ma'] = ma_dict
        commodity_info['sc'] = sc_dict
        commodity_info['fu'] = fu_dict

        finance_info = {}
        finance = ['IF', 'IH', 'IC', 'TF', 'T']

        if_dict = {'code': 'if',
                   'trading_unit': 300,
                   'min_change': 0.2,
                   'margin': 0.15,
                   'commission_fix': 0,
                   'commission_float': 0.00025,
                   'commission_fix_today': 0,
                   'commission_float_today': 0.00025,
                   'exchange_id': 'cffex',
                   'ipo': '2010-04-16',
                   'begintime_local': '2010-04-16 09:15:00',
                   'endtime_local': endtime,
                   'trading_period': [['09:30:00', '11:30:00'],
                                      ['13:00:00', '15:00:00']],
                   'trading_period_mode': '6',
                   'domi_month': ['01', '02', '03', '04', '05', '06',
                                  '07', '08', '09', '12'],
                   }
        ih_dict = {'code': 'ih',
                   'trading_unit': 300,
                   'min_change': 0.2,
                   'margin': 0.15,
                   'commission_fix': 0,
                   'commission_float': 0.00025,
                   'commission_fix_today': 0,
                   'commission_float_today': 0.00025,
                   'exchange_id': 'cffex',
                   'ipo': '2015-04-16',
                   'begintime_local': '2015-04-15 09:30:00',
                   'endtime_local': endtime,
                   'trading_period': [['09:30:00', '11:30:00'],
                                      ['13:00:00', '15:00:00']],
                   'trading_period_mode': '6',
                   'domi_month': ['01', '02', '03', '04', '05', '06',
                                  '07', '08', '09', '12'],
                   }
        ic_dict = {'code': 'ic',
                   'trading_unit': 200,
                   'min_change': 0.2,
                   'margin': 0.08,
                   'commission_fix': 0,
                   'commission_float': 0.00025,
                   'commission_fix_today': 0,
                   'commission_float_today': 0.00025,
                   'exchange_id': 'cffex',
                   'ipo': '2015-04-16',
                   'begintime_local': '2015-04-15 09:30:00',
                   'endtime_local': endtime,
                   'trading_period': [['09:30:00', '11:30:00'],
                                      ['13:00:00', '15:00:00']],
                   'trading_period_mode': '6',
                   'domi_month': ['01', '02', '03', '04', '05', '06',
                                  '07', '08', '09', '12'],
                   }
        tf_dict = {'code': 'tf',
                   'trading_unit': 10000,
                   'min_change': 0.005,
                   'margin': 0.01,
                   'commission_fix': 3,
                   'commission_float': 0,
                   'commission_fix_today': 3,
                   'commission_float_today': 0,
                   'exchange_id': 'cffex',
                   'ipo': '2015-04-16',
                   'begintime_local': '2013-09-06 09:15:00',
                   'endtime_local': endtime,
                   'trading_period': [['09:15:00', '11:30:00'],
                                      ['13:00:00', '15:15:00']],
                   'trading_period_mode': '7',
                   'domi_month': ['03', '06', '09', '12'],

                   }
        t_dict = {'code': 't',
                   'trading_unit': 10000,
                   'min_change': 0.005,
                   'margin': 0.02,
                   'commission_fix': 3,
                   'commission_float': 0,
                   'commission_fix_today': 3,
                   'commission_float_today': 0,
                   'exchange_id': 'cffex',
                   'ipo': '2015-03-20',
                   'begintime_local': '2015-03-20 09:15:00',
                   'endtime_local': endtime,
                   'trading_period': [['09:15:00', '11:30:00'],
                                      ['13:00:00', '15:15:00']],
                   'trading_period_mode': '7',
                   'domi_month': ['01', '02', '03', '04', '05', '06',
                                  '07', '08', '09', '12'],
                   }
        ts_dict = {'code': 'ts',
                  'trading_unit': 20000,
                  'min_change': 0.005,
                  'margin': 0.005,
                  'commission_fix': 3,
                  'commission_float': 0,
                  'commission_fix_today': 3,
                  'commission_float_today': 0,
                  'exchange_id': 'cffex',
                  'ipo': '2018-08-17',
                  'begintime_local': '2018-08-17 09:15:00',
                  'endtime_local': endtime,
                  'trading_period': [['09:15:00', '11:30:00'],
                                     ['13:00:00', '15:15:00']],
                  'trading_period_mode': '7',
                  'domi_month': ['01', '02', '03', '04', '05', '06',
                                 '07', '08', '09', '12'],
                  }
        finance_info['if'] = if_dict
        finance_info['ih'] = ih_dict
        finance_info['ic'] = ic_dict
        finance_info['tf'] = tf_dict
        finance_info['t'] = t_dict
        finance_info['ts'] = ts_dict

        info = commodity_info
        info['if'] = if_dict
        info['ih'] = ih_dict
        info['ic'] = ic_dict
        info['tf'] = tf_dict
        info['t'] = t_dict
        info['ts'] = ts_dict
        return commodity_info, finance_info, info



if __name__ == '__main__':
    # 测试
    self = futures_info()
    commodity_list, finance_list, futures_list = self.futures_list()
    commodity_info, finance_info, info = self.futures_info()
    print('test done!')





